### ISSUE TITLE
Anonymous accounts

### ISSUE THREAD

**Issue by conr2d** [Game-X-Coin/gxc.contracts#11]
## Background

Even though user doesn't have account on GXC, it should not hinder them from playing. In guest mode, `anonymous account` is created and user can claim tokens stored in the balance of anonymous account later.

## Specification

* Token issuer can create anonymous account with public key.
* User can claim tokens in the balance of anonymous account by signing `account_name` with registered public key.

**Comment by conr2d** [comment]
This feature will be supported by `GameXPort`.

**Comment by realcom** [comment]
👍
